USE KpopStore;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Artist
WAITFOR DELAY '00:00:07'
SELECT * FROM Artist
COMMIT TRAN;
INSERT INTO LogTable(typeOp,tableOp,executionDate) VALUES ('Read COM Victim','Artist',CURRENT_TIMESTAMP);
